connectors:
  sms:
    account_sid: "..."
    auth_token: "..."
    phone_number: "+1..."
    is_trial: false
  telegram:
    update-interval: 0.5
    token: "..."
    default-user: "..."
    whitelisted-users:
      - "..."
      - "..."
skills:
  twinkling-tree:
    path: skills.py
